[package]
name = "mem-trace"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]
edition = "2024"

[dependencies]
backtrace = "0.3.56"
dashmap = "4.0.2"
jemallocator = "0.3.2"
libc = "0.2.93"

[features]
profiler = []
tracer = []

[lib]
crate-type = ["dylib"]
