[package]
name = "mem-trace"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3.56"
dashmap = "4.0.2"
jemallocator = "0.3.2"
libc = "0.2.93"
once_cell = "1.7.2"

[lib]
crate-type = ["dylib"]
